name: "Feature request"
description: "Suggest an idea for this project"
title: "[feature]:"
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before you report the bug, please make sure that:
        - You are using the latest version of the project. especially the `main` branch.
        - You have searched the [issues](https://github.com/watergis/svelte-maplibre-components/issues) for similar bug reports.
  - type: textarea
    id: feature-description
    attributes:
      label: "Feature Description"
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: feature-implementation
    attributes:
      label: "Feature Implementation"
      description: "A clear and concise description of how the feature should be implemented."
    validations:
      required: false

  - type: textarea
    id: feature-alternatives
    attributes:
      label: "Feature Alternatives"
      description: "A clear and concise description of any alternative solutions or features you've considered."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: |
        Add any other context or screenshots about the feature request here.`
    validations:
      required: false
