# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.2.4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: lint packages
        run: pnpm --filter="./packages/*" lint
      - name: format packages
        run: pnpm --filter="./packages/*" format
      - name: build packages
        run: pnpm --filter="./packages/*" build
      - name: build sites
        run: |
          pnpm --filter="./sites/svelte.water-gis.com" lint
          pnpm --filter="./sites/svelte.water-gis.com" format
          pnpm --filter="./sites/svelte.water-gis.com" build
      - name: Deploy 🚀
        if: ${{ github.ref == 'refs/heads/main'}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CNAME: ${{secrets.CNAME}}
        run: |
        echo "${CNAME}" >> sites/svelte.water-gis.com/build/CNAME
         git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/watergis/svelte-maplibre-components.git
         pnpm deploy:ghpages
